### ISSUE TITLE
[Suggestion] Visibility for the module 

### ISSUE THREAD

**Issue by zgfg** [adrianmmiller/AppDataIsolation#1]
Please consider submitting to https://github.com/Magisk-Modules-Alt-Repo, to be visible by Fox MMM

Alt Repo is not XDA 😁

**Comment by adrianmmiller** [comment]
hey man,

for reasons we've touched on in the past (Androidacy) i wont be submitting
the modules back to the Alt-Repo, but im
hoping soon they will be more widely available from an alternate source,
since ive severed ties with XDA and theyre
not linked from anywhere currently

feel free to contact me via ***@***.*** for a more private
conversation
